# -*- coding: utf-8 -*-
"""MultiAgent_FinanacialAnalysis_AAI520_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177qQnDrKv-wpBV3_uTihmDwnQcg99qnj
"""

import os
import requests
from datetime import datetime, timedelta
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS # Using FAISS for vector storage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.tools import tool
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_openai import ChatOpenAI # Default LLM for demonstration

# Libraries for new tools
import yfinance as yf
from fredapi import Fred
import re # For SEC parsing

# --- API Keys and Environment Variables ---

NEWS_API_KEY = os.getenv("NEWS_API_KEY")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

FRED_API_KEY = os.getenv("FRED_API_KEY")


# --- LLM Initialization ---
# Changed model from gpt-4o to gpt-3.5-turbo
# Check if OPENAI_API_KEY is not empty and starts with 'sk-'
if OPENAI_API_KEY and OPENAI_API_KEY.startswith("sk-"):
    print("Using provided OpenAI API Key.")
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.0, openai_api_key=OPENAI_API_KEY)
    print("LLM initialized: ChatOpenAI (gpt-3.5-turbo)")
else:
    print("WARNING: OpenAI API Key is not set or is in an incorrect format (does not start with 'sk-'). LLM calls will fail unless you provide a valid key or switch to a local LLM.")
    llm = None

if llm is None:
    print("ERROR: No LLM initialized. Please provide a valid OpenAI API key or configure a local LLM.")
    # Exit logic removed for execution within a continuous environment like Jupyter/Colab/sandbox,
    # but kept as a comment for typical script behavior.
    # exit()

# ==============================================================================
# 2. Data Ingestion Layer
#    - Function to fetch financial news from NewsAPI.org
# ==============================================================================

def fetch_financial_news(api_key, query="finance OR stock market OR economy", language="en", page_size=50, days_ago=7):
    """
    Fetches financial news articles from NewsAPI.org.
    Includes a dummy data fallback if the API key is missing or invalid.
    """
    if not NEWS_API_KEY or NEWS_API_KEY  == "3bf382caa5c24420a03b370cb20f314f": # Check if the key is still a placeholder or empty
        print("Using dummy news data due to missing or placeholder API key.")
        return [
            {'title': "Tech stocks rally as inflation fears ease", 'description': "Major technology companies saw significant gains today as new economic data suggested inflation might be cooling, leading investors to re-evaluate growth stocks.", 'source': {'name': 'Reuters'}, 'publishedAt': '2025-10-10T10:00:00Z', 'url': 'http://example.com/tech-stocks'},
            {'title': "Oil prices jump amid Middle East tensions", 'description': "Crude oil futures surged to multi-year highs following escalating geopolitical tensions in the Middle East, raising concerns about global supply.", 'source': {'name': 'Bloomberg'}, 'publishedAt': '2025-10-09T11:30:00Z', 'url': 'http://example.com/oil-prices'},
            {'title': "Central bank hints at interest rate hike", 'description': "The Federal Reserve chairperson's recent comments indicate a strong possibility of an interest rate increase in the next quarter, aiming to curb persistent inflation.", 'source': {'name': 'Wall Street Journal'}, 'publishedAt': '2025-10-08T14:00:00Z', 'url': 'http://example.com/fed-hike'},
            {'title': "Company X reports record quarterly earnings", 'description': "Leading tech firm Company X announced its best-ever quarterly results, driven by strong demand for its cloud services and enterprise software solutions.", 'source': {'name': 'CNBC'}, 'publishedAt': '2025-10-07T09:15:00Z', 'url': 'http://example.com/company-x'},
            {'title': "Global supply chain disruptions continue to impact manufacturing", 'description': "Manufacturers worldwide are still grappling with severe supply chain bottlenecks, affecting production schedules and leading to higher costs for consumers.", 'source': {'name': 'Financial Times'}, 'publishedAt': '2025-10-06T16:45:00Z', 'url': 'http://example.com/supply-chain'},
            {'title': "New AI breakthrough boosts semiconductor industry outlook", 'description': "A groundbreaking development in AI processing efficiency has sent shares of major semiconductor manufacturers soaring, with analysts predicting sustained growth.", 'source': {'name': 'TechCrunch'}, 'publishedAt': '2025-10-05T08:00:00Z', 'url': 'http://example.com/ai-semiconductors'},
            {'title': "Retail sales exceed expectations in holiday season", 'description': "Despite economic headwinds, consumer spending remained robust during the recent holiday period, with retail sales figures surpassing analyst forecasts.", 'source': {'name': 'MarketWatch'}, 'publishedAt': '2025-10-04T12:00:00Z', 'url': 'http://example.com/retail-sales'},
            {'title': "Cryptocurrency market experiences sharp correction", 'description': "The cryptocurrency market witnessed a significant downturn, with Bitcoin and Ethereum experiencing sharp declines, attributed to regulatory concerns and profit-taking.", 'source': {'name': 'CoinDesk'}, 'publishedAt': '2025-10-03T10:30:00Z', 'url': 'http://example.com/crypto-correction'},
            {'title': "Green energy investments surge globally", 'description': "Investments in renewable energy projects have seen an unprecedented boom, fueled by government incentives and growing corporate commitments to sustainability.", 'source': {'name': 'GreenBiz'}, 'publishedAt': '2025-10-02T15:00:00Z', 'url': 'http://example.com/green-energy'},
            {'title': "Automotive sector faces chip shortage challenges", 'description': "The global automotive industry continues to struggle with a persistent shortage of crucial semiconductor chips, forcing production cuts and impacting new vehicle availability.", 'source': {'name': 'Automotive News'}, 'publishedAt': '2025-10-01T09:00:00Z', 'url': 'http://example.com/auto-chips'}
        ]

    end_date = datetime.now()
    start_date = end_date - timedelta(days=days_ago)

    url = f"https://newsapi.org/v2/everything?q={query}&language={language}&sortBy=publishedAt&pageSize={page_size}&from={start_date.isoformat()}&to={end_date.isoformat()}&apiKey={api_key}"

    print(f"Attempting to fetch news from NewsAPI.org for query: '{query}'...")
    try:
        response = requests.get(url)
        response.raise_for_status()
        articles = response.json().get('articles', [])
        print(f"Successfully fetched {len(articles)} articles from NewsAPI.org.")
        return articles
    except requests.exceptions.HTTPError as errh:
        print(f"Http Error: {errh}")
        if response.status_code == 401:
            print("ERROR: NewsAPI.org API Key is invalid or missing. Please check your key.")
        print(f"Response content: {response.text}")
        return []
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting: {errc}")
        return []
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error: {errt}")
        return []
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong with the request: {err}")
        return []

# ==============================================================================
# 3. Data Processing & Embedding Layer
#    - Text Splitter for chunking documents
#    - HuggingFace Embeddings model
#    - Vector Store (FAISS) for efficient retrieval
# ==============================================================================

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    separators=["\n\n", "\n", " ", ""],
    length_function=len
)
print("Text splitter initialized.")

model_name = "sentence-transformers/all-MiniLM-L6-v2"
# Explicitly set device to 'cpu' for CPU-only environments
embeddings_model = HuggingFaceEmbeddings(model_name=model_name, model_kwargs={'device': 'cpu'})
print(f"Embedding model '{model_name}' initialized successfully on CPU!")

# Global variable for the vector store, to be populated by agents
vectorstore = None

# ==============================================================================
# 4. LLM and Tool Definitions Layer
#    - Custom tools for agents to interact with data and external services
# ==============================================================================

@tool
def search_financial_news(query: str, days_ago: int = 7) -> list[str]:
    """
    Searches for recent financial news articles using NewsAPI.org.
    Returns a list of concise summaries (titles and sources) and updates the global vector store.
    """
    global vectorstore # Declare intent to modify the global vectorstore
    articles_data = fetch_financial_news(NEWS_API_KEY, query=query, days_ago=days_ago)
    financial_documents = []
    for article in articles_data:
        if article.get('title') and article.get('description') and article.get('url'):
            # Using both title and description for content
            page_content = f"Title: {article['title']}\n\n{article['description']}"
            doc = Document(
                page_content=page_content,
                metadata={
                    "title": article['title'],
                    "source": article['source']['name'],
                    "publishedAt": article['publishedAt'],
                    "url": article['url'],
                    "doc_type": "financial_news_api"
                }
            )
            financial_documents.append(doc)

    if financial_documents:
        chunked_docs = text_splitter.split_documents(financial_documents)
        if vectorstore:
            # Create a new FAISS index from the new documents and merge with the existing one
            new_vectorstore = FAISS.from_documents(chunked_docs, embeddings_model)
            vectorstore.merge_from(new_vectorstore)
        else:
            vectorstore = FAISS.from_documents(chunked_docs, embeddings_model)
        print(f"Added {len(chunked_docs)} chunks to vector store from news search.")
    else:
        print("No financial documents generated from news search to add to vector store.")

    # Return a concise summary of documents to prevent cluttering the agent scratchpad too much
    return [
        f"Title: {doc.metadata['title']}, Source: {doc.metadata['source']}"
        for doc in financial_documents[:5]
    ]

@tool
def retrieve_relevant_info(query: str) -> str:
    """
    Retrieves relevant information from the stored financial documents (vector store)
    based on a given query.
    """
    if not vectorstore:
        return "No financial documents have been loaded into the vector store yet. Please ensure news has been searched first."

    retriever = vectorstore.as_retriever(search_kwargs={"k": 5}) # Retrieve top 5 relevant chunks
    relevant_docs = retriever.invoke(query)

    if not relevant_docs:
        return "No relevant information found in the stored documents for the given query."

    # Combine content of relevant documents including metadata
    combined_content = ""
    for i, doc in enumerate(relevant_docs):
        combined_content += (
            f"--- Document {i+1} ---\n"
            f"Title: {doc.metadata.get('title', 'N/A')}\n"
            f"Source: {doc.metadata.get('source', 'N/A')}\n"
            f"Published: {doc.metadata.get('publishedAt', 'N/A')}\n"
            f"Content Snippet: {doc.page_content.replace(doc.metadata.get('title', ''), '').strip()}\n\n"
        )
    return combined_content

@tool
def analyze_sentiment(text: str) -> str:
    """
    Analyzes the sentiment of a given text (e.g., news article, earnings report snippet).
    Returns a concise sentiment label (e.g., 'positive', 'negative', 'neutral') and a brief justification.
    """
    if llm is None:
        return "Sentiment analysis failed: LLM not initialized."

    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a sentiment analysis expert. Analyze the sentiment of the following text and provide a concise sentiment label (positive, negative, neutral) and a brief justification. Only respond with the analysis."),
        ("user", "{text}")
    ])
    chain = prompt | llm
    try:
        # Truncate text for prompt to avoid exceeding context window for long inputs
        truncated_text = text[:4000]
        result = chain.invoke({"text": truncated_text})
        return result.content
    except Exception as e:
        return f"Error during sentiment analysis: {e}"

# --- NEW TOOLS FOR YAHOO FINANCE, FRED, SEC EDGAR ---

@tool
def get_stock_data_yahoo(ticker: str) -> str:
    """
    Fetches current stock price and basic company information (name, sector, industry) for a given ticker symbol from Yahoo Finance.
    Example ticker: "AAPL" for Apple Inc.
    """
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        if not info:
            return f"Could not find data for ticker: {ticker}. Please check the ticker symbol."

        current_price = info.get('currentPrice', 'N/A')
        long_name = info.get('longName', 'N/A')
        sector = info.get('sector', 'N/A')
        industry = info.get('industry', 'N/A')

        return (f"Current stock data for {long_name} ({ticker}):\n"
                f"Price: {current_price}\n"
                f"Sector: {sector}\n"
                f"Industry: {industry}")
    except Exception as e:
        return f"Error fetching stock data for {ticker}: {e}"

@tool
def get_historical_stock_data_yahoo(ticker: str, period: str = "1y") -> str:
    """
    Fetches historical stock prices for a given ticker symbol and period from Yahoo Finance.
    Period options: "1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "10y", "ytd", "max".
    Returns a summary of the historical data (e.g., start price, end price, high, low).
    """
    try:
        stock = yf.Ticker(ticker)
        hist = stock.history(period=period)
        if hist.empty:
            return f"No historical data found for {ticker} for period {period}. Please check ticker and period."

        start_date = hist.index[0].strftime('%Y-%m-%d')
        end_date = hist.index[-1].strftime('%Y-%m-%d')
        open_price = hist['Open'].iloc[0]
        close_price = hist['Close'].iloc[-1]
        high_price = hist['High'].max()
        low_price = hist['Low'].min()

        return (f"Historical stock data for {ticker} ({period}):\n"
                f"Period: {start_date} to {end_date}\n"
                f"Start Open Price: {open_price:.2f}\n"
                f"End Close Price: {close_price:.2f}\n"
                f"Highest Price: {high_price:.2f}\n"
                f"Lowest Price: {low_price:.2f}")
    except Exception as e:
        return f"Error fetching historical stock data for {ticker}: {e}"

@tool
def get_fred_series(series_id: str, observation_start: str = None, observation_end: str = None) -> str:
    """
    Fetches a specific economic data series from the Federal Reserve Economic Data (FRED) API.
    Requires a FRED API key.
    Example series_id: "GDP" (Gross Domestic Product), "CPIAUCSL" (CPI for All Urban Consumers).
    observation_start and observation_end should be in 'YYYY-MM-DD' format.
    """
    if not FRED_API_KEY or FRED_API_KEY == "7957b30df36846c6a20737cdb3d3a70a":
        return "FRED API Key is not set. Cannot fetch FRED data. Using dummy data for demonstration."
        # Dummy data for FRED
        if series_id == "GDP":
            return "Dummy FRED data for GDP: Q1 2025: 28.0T, Q4 2024: 27.8T, Q3 2024: 27.5T"
        elif series_id == "CPIAUCSL":
            return "Dummy FRED data for CPIAUCSL: Sep 2025: 310.5, Aug 2025: 310.2, Jul 2025: 309.8"
        else:
            return f"Dummy FRED data for {series_id}: No specific dummy data, assuming stable."

    try:
        fred = Fred(api_key=FRED_API_KEY)
        data = fred.get_series(series_id, observation_start=observation_start, observation_end=observation_end)

        if data.empty:
            return f"No data found for FRED series ID: {series_id}. Please check the series ID."

        latest_data = data.tail(5) # Get last 5 observations
        result_str = f"FRED Series: {series_id}\n"
        for date, value in latest_data.items():
            result_str += f"{date.strftime('%Y-%m-%d')}: {value:.2f}\n"
        return result_str
    except Exception as e:
        return f"Error fetching FRED series {series_id}: {e}"

@tool
def search_sec_filings(company_name: str, form_type: str = "10-K", limit: int = 3) -> str:
    """
    Searches for recent SEC filings (e.g., 10-K, 10-Q) for a given company.
    Returns a list of filing URLs and their dates.
    """
    # SEC EDGAR API requires a User-Agent header
    headers = {'User-Agent': 'sabinageorge@sandiego.edu'} # Replace with your actual info
    search_url = f"https://www.sec.gov/cgi-bin/browse-edgar?company={company_name}&owner=exclude&action=getcompany&type={form_type}&count={limit}"

    print(f"Searching SEC filings for {company_name} ({form_type})...")
    try:
        response = requests.get(search_url, headers=headers)
        response.raise_for_status()

        # This is a very basic HTML parsing. A more robust solution would use BeautifulSoup.
        # We're looking for links to the filing documents.
        filings = []
        # Regex to find links that typically point to the actual filing document within the SEC page
        # Example: /Archives/edgar/data/1000045/000100004523000003/aapl-20230930.htm
        # Or: /Archives/edgar/data/1000045/000100004523000003/

        # Find all <a> tags that contain 'Archives/edgar/data/' and 'type=HTML' or similar patterns
        # This regex is simplified and might need tuning for robustness
        # Looking for links to the "Documents" page for each filing
        doc_links = re.findall(r'href="(/Archives/edgar/data/[0-9]+/[0-9]+/.*?)"', response.text)

        unique_doc_links = []
        seen_urls = set()
        for link in doc_links:
            full_link = f"https://www.sec.gov{link}"
            # Filter for unique base document links (often multiple links point to the same filing)
            if full_link not in seen_urls:
                unique_doc_links.append(full_link)
                seen_urls.add(full_link)
            if len(unique_doc_links) >= limit:
                break

        if not unique_doc_links:
            return f"No recent {form_type} filings found for {company_name}."

        result_str = f"Recent {form_type} filings for {company_name}:\n"
        for i, link in enumerate(unique_doc_links):
            result_str += f"  {i+1}. {link}\n"
            if i >= limit -1: # Limit to requested number
                break
        return result_str

    except requests.exceptions.RequestException as e:
        return f"Error searching SEC filings for {company_name}: {e}"
    except Exception as e:
        return f"An unexpected error occurred during SEC filing search: {e}"

# ==============================================================================
# 5. Agent Definitions Layer (Agent Functions)
#    - Specialized agents with specific roles, tools, and prompts
# ==============================================================================

# List of all tools available to the system
ALL_TOOLS = [
    search_financial_news,
    retrieve_relevant_info,
    analyze_sentiment,
    get_stock_data_yahoo,
    get_historical_stock_data_yahoo,
    get_fred_series,
    search_sec_filings
]

# --- News Analyst Agent ---
news_analyst_prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a specialized News Analyst. Your primary goal is to find relevant financial news and summarize it concisely. "
     "You have access to the provided tools. Use 'search_financial_news' to fetch articles and 'retrieve_relevant_info' to access the stored news documents. After retrieving, always summarize the key findings."),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])
news_analyst_agent = create_tool_calling_agent(llm, [search_financial_news, retrieve_relevant_info], news_analyst_prompt)
news_analyst_executor = AgentExecutor(agent=news_analyst_agent, tools=[search_financial_news, retrieve_relevant_info], verbose=True, handle_parsing_errors=True)
print("News Analyst Agent created with create_tool_calling_agent.")

# --- Financial Analyst Agent ---
financial_analyst_prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a specialized Financial Analyst. Your role is to analyze financial information, identify trends, assess impact, and provide insights. "
     "You have access to the following tools: 'retrieve_relevant_info' for news, 'analyze_sentiment' for text, "
     "'get_stock_data_yahoo' for current stock price/info, 'get_historical_stock_data_yahoo' for historical prices, "
     "'get_fred_series' for macroeconomic data, and 'search_sec_filings' for company reports. "
     "Always provide a clear financial assessment based on the available information."),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])
financial_analyst_agent = create_tool_calling_agent(llm, ALL_TOOLS, financial_analyst_prompt) # Give all tools to financial analyst
financial_analyst_executor = AgentExecutor(agent=financial_analyst_agent, tools=ALL_TOOLS, verbose=True, handle_parsing_errors=True)
print("Financial Analyst Agent created with create_tool_calling_agent and all tools.")

# --- Reporter Agent ---
reporter_prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a professional Financial Reporter. Your task is to synthesize information from various sources and generate a clear, concise, and well-structured financial report. "
     "You have access to the provided tools, including 'retrieve_relevant_info' for news and analysis data. Ensure the report is easy to understand and highlights key findings."),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])
reporter_agent = create_tool_calling_agent(llm, [retrieve_relevant_info], reporter_prompt) # Reporter only needs retrieval tool for generated summaries
reporter_executor = AgentExecutor(agent=reporter_agent, tools=[retrieve_relevant_info], verbose=True, handle_parsing_errors=True)
print("Reporter Agent created with create_tool_calling_agent.")

# ==============================================================================
# 6. Workflow Patterns Layer (LOGICAL FIX APPLIED)
#    - Orchestrates interactions between agents for specific tasks
# ==============================================================================

def daily_market_briefing_workflow(query: str = "global financial markets", days_ago: int = 1) -> str:
    """
    Workflow to generate a daily market briefing.
    1. Explicitly fetch news and populate vector store. (Step 0)
    2. News Analyst summarizes the new data.
    3. Financial Analyst analyzes the overall market sentiment and impact.
    4. Reporter synthesizes information into a daily briefing report.
    """
    print("\n" + "="*60)
    print(f"--- Starting Daily Market Briefing Workflow for '{query}' (last {days_ago} days) ---")
    print("="*60)
    global vectorstore # Ensure access to the global variable
    chat_history = []

    # Step 0: Data Ingestion - Directly call the tool's underlying function to guarantee vectorstore population
    print("\n[Data Ingestion] Forcing News API call and vector store population...")
    search_results_summary = search_financial_news.func(query=query, days_ago=days_ago) # FIX APPLIED HERE
    chat_history.append(AIMessage(content=f"Successfully ingested news data. Key headlines: {search_results_summary}"))

    # Step 1: News Analyst summarizes (now from the populated vector store)
    print("\n[News Analyst] Summarizing recent financial news from the vector store...")
    news_input = f"Based on the news data just ingested (for {query}), use **retrieve_relevant_info** to fetch the content and provide a concise summary of major headlines and their implications."
    news_analysis_response = news_analyst_executor.invoke({
        "input": news_input,
        "chat_history": chat_history,
    })
    news_summary = news_analysis_response['output']
    chat_history.append(HumanMessage(content=news_input))
    chat_history.append(AIMessage(content=news_summary))
    print(f"\nNews Analyst Summary:\n{news_summary}")

    # Step 2: Financial Analyst analyzes the market sentiment based on the retrieved news
    print("\n[Financial Analyst] Analyzing overall market sentiment and potential impact...")
    financial_input = f"Based on the recent news about {query} (summarized as: '{news_summary}'), what is the overall market sentiment and its potential impact on investors? Use the available information by using **retrieve_relevant_info** to provide a clear assessment."
    financial_analysis_response = financial_analyst_executor.invoke({
        "input": financial_input,
        "chat_history": chat_history,
    })
    financial_assessment = financial_analysis_response['output']
    chat_history.append(HumanMessage(content=financial_input))
    chat_history.append(AIMessage(content=financial_assessment))
    print(f"\nFinancial Analyst Report:\n{financial_assessment}")

    # Step 3: Reporter generates the final briefing
    print("\n[Reporter] Generating daily market briefing report...")
    report_input = (
        f"Generate a comprehensive daily market briefing for '{query}' based on the following information:\n\n"
        f"**Recent News Summary:**\n{news_summary}\n\n"
        f"**Financial Analyst's Assessment:**\n{financial_assessment}\n\n"
        "Structure the report with a clear title, key headlines, overall market sentiment, and a brief outlook."
    )
    final_briefing_response = reporter_executor.invoke({
        "input": report_input,
        "chat_history": chat_history,
    })
    final_briefing = final_briefing_response['output']

    print("\n" + "="*60)
    print("--- Daily Market Briefing Workflow Completed ---")
    print("="*60)
    return final_briefing

def comprehensive_company_analysis_workflow(ticker: str, company_name: str, news_days_ago: int = 14, fred_series_id: str = "CPIAUCSL") -> str:
    """
    Workflow for a comprehensive company analysis, using multiple data sources.
    1. Fetch company-specific news and populate vector store.
    2. Fetch stock data (current and historical).
    3. Fetch relevant macroeconomic data.
    4. Search for SEC filings.
    5. Financial Analyst synthesizes all this information.
    6. Reporter generates a detailed report.
    """
    print("\n" + "#"*70)
    print(f"### Starting Comprehensive Company Analysis Workflow for '{company_name}' ({ticker}) ###")
    print("#"*70)
    global vectorstore
    chat_history = []

    # Step 0a: Data Ingestion - Company-specific news
    print(f"\n[Data Ingestion] Fetching company news for {company_name}...")
    news_query = f'"{company_name}" OR "{ticker}" stock OR "{company_name}" earnings'
    news_search_summary = search_financial_news.func(query=news_query, days_ago=news_days_ago)
    chat_history.append(AIMessage(content=f"Successfully ingested news data for {company_name}. Key headlines: {news_search_summary}"))

    # Step 0b: Financial Analyst fetches stock data, FRED data, and SEC filings
    print(f"\n[Financial Analyst] Gathering stock data, FRED data, and SEC filings for {company_name}...")

    # Get current stock data
    stock_data = get_stock_data_yahoo.func(ticker=ticker)
    chat_history.append(AIMessage(content=f"Stock Data for {ticker}: {stock_data}"))

    # Get historical stock data
    historical_data = get_historical_stock_data_yahoo.func(ticker=ticker, period="1y")
    chat_history.append(AIMessage(content=f"Historical Stock Data for {ticker}: {historical_data}"))

    # Get FRED data
    fred_data = get_fred_series.func(series_id=fred_series_id, observation_start=(datetime.now() - timedelta(days=365)).strftime('%Y-%m-%d'))
    chat_history.append(AIMessage(content=f"FRED Data ({fred_series_id}): {fred_data}"))

    # Search SEC filings
    sec_filings = search_sec_filings.func(company_name=company_name, form_type="10-K", limit=1)
    chat_history.append(AIMessage(content=f"SEC Filings for {company_name}: {sec_filings}"))

    # Step 1: Financial Analyst synthesizes all gathered information
    print(f"\n[Financial Analyst] Synthesizing all data for {company_name}...")
    analysis_input = (
        f"Perform a comprehensive financial analysis for {company_name} ({ticker}) based on the following:\n"
        f"**Recent News:** Use retrieve_relevant_info to summarize key news about {company_name}.\n"
        f"**Stock Data:** Current: {stock_data}. Historical (1yr): {historical_data}.\n"
        f"**Macroeconomic Data:** FRED Series {fred_series_id}: {fred_data}.\n"
        f"**SEC Filings:** {sec_filings}.\n\n"
        "Analyze trends, potential impacts, and provide a clear investment outlook (e.g., Buy, Hold, Sell) with justification."
    )
    financial_analysis_response = financial_analyst_executor.invoke({
        "input": analysis_input,
        "chat_history": chat_history,
    })
    comprehensive_analysis = financial_analysis_response['output']
    chat_history.append(HumanMessage(content=analysis_input))
    chat_history.append(AIMessage(content=comprehensive_analysis))
    print(f"\nFinancial Analyst's Comprehensive Analysis for {company_name}:\n{comprehensive_analysis}")

    # Step 2: Reporter generates the final comprehensive report
    print(f"\n[Reporter] Generating comprehensive report for {company_name}...")
    report_input = (
        f"Generate a comprehensive financial report for {company_name} ({ticker}). "
        f"Include sections for: Executive Summary, Recent News Highlights, Stock Performance (Current & Historical), "
        f"Macroeconomic Context, Key Financial Filings, Financial Analyst's Outlook, and Conclusion. "
        f"Base this on the following synthesized analysis:\n\n{comprehensive_analysis}\n\n"
        "Ensure the report is professional, well-structured, and easy to understand."
    )
    final_report_response = reporter_executor.invoke({
        "input": report_input,
        "chat_history": chat_history,
    })
    final_report = final_report_response['output']

    print("\n" + "#"*70)
    print(f"### Comprehensive Company Analysis Workflow for '{company_name}' Completed ###")
    print("#"*70)
    return final_report



if __name__ == "__main__":
    if llm is None:
        print("\nSkipping execution because the LLM failed to initialize.")
    else:
        # ==============================================================================
# 7. Main Execution Logic
#    - Demonstrates how to run the defined workflows
# ==============================================================================rint("\n" + "#"*70)
        print("### Multi-Agent Financial Analysis System Initialized and Running ###")
        print("#"*70)

        # --- Run Workflow 1: Daily Market Briefing ---
        # Reset vectorstore explicitly before the first run (optional but safe)
        vectorstore = None
        daily_briefing_output = daily_market_briefing_workflow(query="US stock market and inflation", days_ago=2)
        print("\n\n" + "="*70)
        print("                 FINAL DAILY MARKET BRIEFING REPORT                 ")
        print("="*70)
        print(daily_briefing_output)
        print("="*70)

        # --- Run Workflow 2: Comprehensive Company Analysis (User Input) ---
        print("\n\n" + "#"*70)
        print("### Comprehensive Company Analysis (User Input) ###")
        print("#"*70)

        user_ticker = input("Enter the stock ticker symbol (e.g., NVDA, AAPL): ").strip().upper()
        user_company_name = input(f"Enter the full company name for {user_ticker} (e.g., NVIDIA, Apple): ").strip()

        if not user_ticker or not user_company_name:
            print("Ticker symbol or company name cannot be empty. Skipping company analysis.")
        else:
            vectorstore = None # Reset vector store for a fresh start for the next workflow
            company_report_output = comprehensive_company_analysis_workflow(
                ticker=user_ticker,
                company_name=user_company_name,
                news_days_ago=14,
                fred_series_id="CPIAUCSL"
            )
            print("\n\n" + "="*70)
            print(f"          FINAL COMPREHENSIVE REPORT FOR {user_company_name.upper()}           ")
            print("="*70)
            print(company_report_output)
            print("="*70)

            # --- Extract and print recommendation ---
            recommendation = "No specific investment outlook found in the report."

            # Look for the "Financial Analyst's Outlook" section, which is a guaranteed section header
            # This regex captures everything after "Financial Analyst's Outlook:" until the next section header or end of string.
            match = re.search(r"Financial Analyst's Outlook:\s*\n*(.*?)(?=\n\n[A-Z][a-zA-Z\s]+:|\Z)", company_report_output, re.DOTALL)

            if match:
                outlook_section = match.group(1).strip()
                # Within this section, try to extract a more concise recommendation if possible
                # Look for phrases like "Investment Outlook:", "Recommendation:", "Verdict:", "Our Stance:"
                concise_match = re.search(r"(Investment Outlook|Recommendation|Verdict|Our Stance):\s*(.*?)(?=\n|\Z)", outlook_section, re.DOTALL | re.IGNORECASE)
                if concise_match:
                    recommendation = concise_match.group(2).strip()
                else:
                    recommendation = outlook_section # Fallback to the entire section if no concise phrase is found

            print("\n" + "#"*70)
            print(f"### Investment Recommendation for {user_company_name} ({user_ticker}): ###")
            print(recommendation)
            print("#"*70)

        print("\n" + "#"*70)
        print("### Financial Analysis System execution finished. ###")
        print("#"*70)
